FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    autoconf \
    automake \
    libtool \
    git \
    pkg-config \
    socat \
    time \
    libmodbus-dev

WORKDIR /app
